name: The Apiary Group
markdown: redcarpet
pygments: true
permalink: /:categories/:title

tagline: |
  We make pretty things. And useful things. And silly things we find pretty or useful.<br /><br />

overview: |
  We're a group of dedicated upstarts who like to make things.<br />
  We've got a range of skills running the gamut from technical to creative.<br />
  We've got a passion for detail.<br />
  We work on what we love.

links:
- name: email
  link: mailto:theapiarygroup@gmail.com
- name: Twitter
  link: https://twitter.com/theapiaryco
- name: GitHub
  link: https://github.com/The-Apiary

prose:
  rooturl: '_posts'
  siteurl: 'http://the-apiary.github.io'
  media: 'media'
  metadata:
    _posts/posts:
      - name: "categories"
        field:
          element: "hidden"
          value: "posts"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/people:
      - name: "categories"
        field:
          element: "hidden"
          value: "people"
      - name: "layout"
        field:
          element: "hidden"
          value: "person"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/ideas:
      - name: "categories"
        field:
          element: "hidden"
          value: "ideas"
      - name: "layout"
        field:
          element: "hidden"
          value: "idea"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
